import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {JSDOM} from 'jsdom';
import {parseCrmFilters,queryCrm} from '../lib/crm-query.js';
const now=new Date('2026-10-07T18:00:00Z');
async function until(fn){for(let n=0;n<100;n++){if(fn())return;await new Promise(r=>setTimeout(r,5))}throw new Error('UI condition not reached')}
test('overview drills down, profile saves, report exports and logout removes private data',async()=>{
 const html=fs.readFileSync(new URL('../public/dashboard.html',import.meta.url),'utf8');const dom=new JSDOM(html,{url:'https://dashboard.example',runScripts:'outside-only'});const w=dom.window;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
 const record={id:'crm-a',submittedContact:{name:'<img src=x onerror=alert(1)>',email:'a@example.test',organization:'Test Ministry'},correctedContact:{},consent:{email:null,text:null,terms:null},originalSubmission:{contact_name:'Original name'},sourceTable:'partner_leads',receivedAt:'2026-10-07T12:00:00Z',category:'Ministry Partner',workflowStatus:'New',partnerStage:'Inquiry',revision:1,followUpDate:null};
 const store={crmRecords:[record]},sources=[{source:'partner_leads',status:'Connected',lastSuccessAt:now.toISOString(),importedCount:1}],activities=[];
 const api=async(url,opt={})=>{const u=new URL(url,'https://dashboard.example');const filters=parseCrmFilters(Object.fromEntries(u.searchParams),now);if(u.pathname==='/api/crm/overview')return {total:1,partners:1,overdue:0,filters,partnerFilters:{...filters,preset:'partnership_pipeline'},overdueFilters:parseCrmFilters({range:'all',preset:'follow_up',followUp:'overdue'},now),sources};if(u.pathname==='/api/crm/records/crm-a'){if(opt.method==='PATCH'){const p=JSON.parse(opt.body);assert.equal(p.revision,record.revision);Object.assign(record,{...p,revision:record.revision+1});activities.push({action:'crm.update',actorName:'Owner',createdAt:now.toISOString(),changedFields:['workflowStatus'],note:p.note||''})}return {record:structuredClone(record),activities,relatedPurchases:[]}}return {...queryCrm(store,filters,{paginate:u.pathname!=='/api/crm/reports'}),sources,generatedAt:now.toISOString()}};
 w.eval(fs.readFileSync(new URL('../public/crm-dashboard.js',import.meta.url),'utf8'));w.KVNCrm.init({api,user:{role:'owner'},showPanel:name=>{w.document.querySelectorAll('.panel').forEach(e=>e.classList.toggle('active',e.id==='panel-'+name))}});
 await until(()=>w.document.querySelector('[data-total="1"]'));w.document.querySelector('[data-total="1"]').click();await until(()=>w.document.querySelector('#crm-results-partners [data-record]'));assert.equal(w.document.querySelector('#panel-partners').classList.contains('active'),true);assert.equal(w.document.querySelectorAll('#crm-results-partners img').length,0);
 w.document.querySelector('#crm-results-partners [data-record]').click();await until(()=>w.document.querySelector('#crm-edit'));const form=w.document.querySelector('#crm-edit');form.elements.workflowStatus.value='Contacted';form.elements.note.value='Follow up next week';form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>w.document.querySelector('#crm-detail-notice')?.textContent==='Changes saved.');assert.equal(record.workflowStatus,'Contacted');assert.deepEqual(Object.keys(record.correctedContact),[],'a note/status save must not freeze source contact values');assert.equal(record.categoryOverride,undefined);assert.ok(w.document.querySelector('#crm-detail').textContent.includes('Follow up next week'));
 w.document.querySelector('#crm-close').click();w.KVNCrm.open('reports',{range:'all',preset:'partnership_pipeline'});await until(()=>!w.document.querySelector('#crm-export-reports').hidden);assert.ok(w.document.querySelector('#crm-summary-reports').textContent.startsWith('1 records'));assert.ok(w.document.querySelector('#crm-export-reports').href.includes('preset=partnership_pipeline'));w.KVNCrm.clear();assert.equal(w.document.querySelector('#panel-reports').textContent,'');assert.equal(w.document.querySelector('#crm-detail').textContent,'');dom.window.close();
});
test('delayed save cannot reopen a dialog after logout',async()=>{
 const dom=new JSDOM(fs.readFileSync(new URL('../public/dashboard.html',import.meta.url),'utf8'),{url:'https://dashboard.example',runScripts:'outside-only'}),w=dom.window;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
 let release,started=false;const record={id:'a',category:'Vendor',submittedContact:{name:'Alice',email:'a@example.test'},correctedContact:{},consent:{},workflowStatus:'New',partnerStage:'Inquiry',revision:1,receivedAt:now.toISOString(),sourceTable:'partner_leads'};
 const api=async(url,opt={})=>{if(opt.method==='PATCH'){started=true;await new Promise(r=>release=r);return {record}}if(url.includes('/records/a'))return {record,activities:[],relatedPurchases:[]};if(url.includes('/overview'))return {total:1,partners:1,overdue:0,filters:parseCrmFilters({},now),sources:[]};return {rows:[record],total:1,filters:parseCrmFilters({},now),sources:[],generatedAt:now.toISOString()}};
 w.eval(fs.readFileSync(new URL('../public/crm-dashboard.js',import.meta.url),'utf8'));w.KVNCrm.init({api,user:{role:'owner'},showPanel:()=>{}});w.KVNCrm.open('crm');await until(()=>w.document.querySelector('#crm-results-crm [data-record]'));w.document.querySelector('#crm-results-crm [data-record]').click();await until(()=>w.document.querySelector('#crm-edit'));const form=w.document.querySelector('#crm-edit');form.elements.note.value='Delayed save';form.dispatchEvent(new w.Event('submit',{cancelable:true}));await until(()=>started);w.KVNCrm.clear();release();await new Promise(r=>setTimeout(r,30));assert.equal(w.document.querySelector('#crm-detail').open,false);assert.equal(w.document.querySelector('#crm-detail').textContent,'');dom.window.close();
});
test('early-access success does not turn unavailable partner sources into zero',async()=>{const dom=new JSDOM(fs.readFileSync(new URL('../public/dashboard.html',import.meta.url),'utf8'),{url:'https://dashboard.example',runScripts:'outside-only'}),w=dom.window;w.eval(fs.readFileSync(new URL('../public/crm-dashboard.js',import.meta.url),'utf8'));w.KVNCrm.init({user:{role:'owner'},showPanel:()=>{},api:async()=>({total:7,partners:0,overdue:0,filters:parseCrmFilters({},now),sources:[{source:'early_access_leads',status:'Connected',lastSuccessAt:now.toISOString()},{source:'partner_leads',status:'Unavailable'},{source:'kingdom_market_applications',status:'Unavailable'}]})});await until(()=>w.document.querySelector('[data-total="1"]'));assert.equal(w.document.querySelector('[data-total="1"] strong').textContent,'—');assert.ok(w.document.querySelector('[data-total="0"]').textContent.includes('Partial'));dom.window.close()});
