import test from 'node:test';import assert from 'node:assert/strict';
import { receiveDiscipleApplication } from '../lib/disciple-intake.js';
import { DISCIPLE_AGREEMENT_TEXT,agreementHash } from '../lib/disciple-agreement.js';
const payload={legalFirstName:'Briannah',legalLastName:'Cooper',preferredName:'Briannah',email:'briannah@example.com',mobile:'919-555-1212',address1:'1 Main',city:'Sanford',state:'NC',postalCode:'27330',country:'US',shirtSize:'XL',market:'RDU',instagram:'@briannah',audienceSize:100,motivation:'Serve',promotionPlan:'Post',weeklyPostCommitment:true,agreementAccepted:true,electronicRecordsConsent:true,recordsAccessConfirmed:true,typedLegalName:'Briannah Cooper',agreementVersion:'2.2',agreementHash:agreementHash(DISCIPLE_AGREEMENT_TEXT)};
const evidence={idempotencyKey:'idem-12345678',sourceSystem:'kvnlive-site',ip:'203.0.113.5',userAgent:'test'};
test('creates once and returns the same application for an idempotent retry',()=>{const store={discipleApplications:[],auditLogs:[]},deps={id:prefix=>`${prefix}_1`,now:()=> '2026-09-21T20:00:00.000Z'};const first=receiveDiscipleApplication(store,payload,evidence,deps),retry=receiveDiscipleApplication(store,payload,evidence,deps);assert.equal(first.created,true);assert.equal(retry.created,false);assert.equal(store.discipleApplications.length,1);assert.equal(retry.application.applicationReference,first.application.applicationReference);});
test('flags duplicate email without rejecting the new submission',()=>{const store={discipleApplications:[{email:'briannah@example.com',mobile:'+10000000000',status:'submitted'}],auditLogs:[]};const result=receiveDiscipleApplication(store,payload,{...evidence,idempotencyKey:'idem-different'},{id:p=>`${p}_2`,now:()=> '2026-09-21T20:00:00.000Z'});assert.equal(result.application.duplicateRisk,true);assert.equal(store.discipleApplications.length,2);});
test('retains only an active Leader recruiting attribution without assigning a team',()=>{const store={discipleApplications:[],disciples:[{id:'leader-1',handle:'leaderone',status:'active',isKingdomLeader:true},{id:'inactive',handle:'oldleader',status:'active',isKingdomLeader:false}],discipleTeams:[],auditLogs:[]};const deps={id:p=>`${p}_3`,now:()=> '2026-09-21T20:00:00.000Z'};const active=receiveDiscipleApplication(store,{...payload,recruitingLeaderHandle:'LeaderOne'},evidence,deps);assert.equal(active.application.recruitingLeaderHandle,'leaderone');assert.equal(active.application.recruitingLeaderId,'leader-1');assert.equal(store.discipleTeams.length,0);const unknown=receiveDiscipleApplication(store,{...payload,email:'other@example.com',mobile:'9195553434',recruitingLeaderHandle:'missing'},{...evidence,idempotencyKey:'idem-unknown'},deps);assert.equal(unknown.application.recruitingLeaderHandle,'');assert.equal(unknown.application.recruitingLeaderId,'');assert.equal(store.discipleTeams.length,0);});
test('trusted legacy transfer preserves its original reference agreement and timestamps without making it approval-eligible',()=>{const store={discipleApplications:[],auditLogs:[]};const legacy={...payload,legacyApplicationId:'legacy-1',legacyApplicationReference:'KVN-D-20260907-D95ABD81',legacyStatus:'submitted',agreementVersion:'1.0',agreementHash:'a'.repeat(64),agreementAcceptedAt:'2026-09-07T14:15:00.000Z',submittedAt:'2026-09-07T14:16:00.000Z',sourceSubmissionIp:'203.0.113.10',sourceUserAgent:'Legacy browser'};const result=receiveDiscipleApplication(store,legacy,{...evidence,idempotencyKey:'legacy:KVN-D-20260907-D95ABD81',sourceSystem:'kvnlive-site-legacy'},{id:p=>`${p}_4`,now:()=> '2026-09-25T20:00:00.000Z',allowLegacyAgreement:true});assert.equal(result.application.applicationReference,legacy.legacyApplicationReference);assert.equal(result.application.agreementVersion,'1.0');assert.equal(result.application.agreementAcceptedAt,legacy.agreementAcceptedAt);assert.equal(result.application.submittedAt,legacy.submittedAt);assert.equal(result.application.submissionIp,legacy.sourceSubmissionIp);assert.equal(result.application.status,'submitted');});
