import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {JSDOM} from 'jsdom';
const tick=()=>new Promise(r=>setTimeout(r,0));
async function setup(t,clean=async()=>({valid:1,inputRows:1,duplicates:0,rejectedCount:0,csv:'email\na@example.com'})){
 const dom=new JSDOM('<div id="marketingRoot"></div><dialog id="marketingDialog"></dialog>',{runScripts:'outside-only',url:'https://example.test'}),w=dom.window;t.after(()=>w.close());w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};let imports=0;
 const state={lists:[],contacts:[],total:0,page:1,settings:{mailingAddress:'123 Test'},configured:true,campaigns:[]};w.eval(fs.readFileSync('public/marketing-dashboard.js','utf8'));w.KVNMarketing.init({user:{role:'owner'},api:async(url)=>{if(url.includes('clean-csv'))return clean();if(url.endsWith('/import')){imports++;return {imported:1,added:1,merged:0}}return state}});await tick();const $=id=>w.document.getElementById(id);$('mImport').click();let files=[];Object.defineProperty($('miFile'),'files',{get:()=>files});return {w,$,imports:()=>imports,select(name){files=[{name,size:30,text:async()=> 'email\na@example.com'}];$('miFile').dispatchEvent(new w.Event('change'))},remove(){files=[];$('miRemove').click()}};
}
test('remove file clears cleanup and disables import; Back and Close exit without saving',async t=>{const h=await setup(t);h.select('one.csv');h.$('miClean').click();await tick();assert.equal(h.$('miSubmit').disabled,false);assert.ok(h.$('miRemove'));h.remove();assert.equal(h.$('miSubmit').disabled,true);assert.equal(h.$('miDownload').disabled,true);h.$('marketingBack').click();assert.equal(h.$('marketingDialog').open,false);h.$('mImport').click();h.$('marketingClose').click();assert.equal(h.$('marketingDialog').open,false);assert.equal(h.imports(),0)});
test('late cleanup cannot enable import after selecting a different file',async t=>{let resolve;const h=await setup(t,()=>new Promise(r=>resolve=r));h.select('one.csv');h.$('miClean').click();await tick();h.select('two.csv');resolve({valid:1,inputRows:1,duplicates:0,rejectedCount:0,csv:'old'});await tick();assert.equal(h.$('miSubmit').disabled,true);assert.equal(h.$('miSummary').textContent,'');});
test('Escape clears dialog and ignores pending cleanup',async t=>{let resolve;const h=await setup(t,()=>new Promise(r=>resolve=r));h.select('one.csv');h.$('miClean').click();await tick();h.$('marketingDialog').dispatchEvent(new h.w.Event('cancel',{cancelable:true}));resolve({valid:1,inputRows:1,duplicates:0,rejectedCount:0,csv:'old'});await tick();assert.equal(h.$('marketingDialog').open,false);assert.equal(h.$('marketingDialog').innerHTML,'')});
test('Back to File preserves selection and clears preview; file chooser and cancel controls work',async t=>{const h=await setup(t);let picks=0;h.$('miFile').click=()=>picks++;h.$('miChoose').click();assert.equal(picks,1);h.select('one.csv');h.$('miLabel').value='My audience';h.$('miClean').click();await tick();h.$('marketingBack').click();assert.equal(h.$('marketingDialog').open,true);assert.equal(h.$('miLabel').value,'My audience');assert.equal(h.$('miFile').files[0].name,'one.csv');assert.equal(h.$('miSubmit').disabled,true);h.$('miCancel').click();assert.equal(h.$('marketingDialog').open,false)});
test('cleanup downloads and import use reformatted deduplicated contacts only',async t=>{
 const {cleanCsv,importContacts,ensureMarketing}=await import('../lib/marketing.js');const disk=ensureMarketing({});let importedBody;
 const h=await setup(t);h.w.KVNMarketing.clear();h.w.KVNMarketing.init({user:{role:'owner'},api:async(url,opt)=>{if(url.includes('clean-csv')){const r=cleanCsv(JSON.parse(opt.body).csv);return {...r,valid:r.rows.length,rejectedCount:r.rejected.length,sample:r.rows.slice(0,5)}}if(url.endsWith('/import')){importedBody=JSON.parse(opt.body);return importContacts(disk,importedBody)}return {lists:[],contacts:[],total:0,page:1,settings:{mailingAddress:'123 Test'},configured:true,campaigns:[]}}});await tick();h.$('mImport').click();Object.defineProperty(h.$('miFile'),'files',{value:[{name:'raw.csv',size:100,text:async()=> 'Email Address,Name\n A@EXAMPLE.COM ,Alice\na@example.com,Alice\ninvalid,Bad'}]});h.$('miFile').onchange();h.$('miClean').click();await tick();assert.match(h.$('miSummary').textContent,/1 unique contacts/);assert.equal(h.$('miSample').textContent,'a@example.comAlice');let downloads=0;h.w.URL.createObjectURL=()=> 'blob:test';h.w.URL.revokeObjectURL=()=>{};h.w.HTMLAnchorElement.prototype.click=function(){downloads++};h.$('miDownload').click();h.$('miRejected').click();assert.equal(downloads,2);h.$('mImportForm').dispatchEvent(new h.w.Event('submit',{cancelable:true}));await tick();assert.equal(disk.marketing.contacts.length,1);assert.equal(disk.marketing.contacts[0].email,'a@example.com');assert.ok(!importedBody.csv.includes('invalid'));assert.equal(h.$('marketingDialog').open,false);
});
