import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {registerPerformanceAgreementRoutes} from '../lib/performance-agreement-routes.js';
import {digest} from '../lib/performance-agreements.js';
const draft={eventKey:'future-event',name:'Test Signer',email:'test@example.com',text:'Approved test terms.'};
async function fixture(t,options={}){let disk={agreements:[],sync:{at:new Date().toISOString(),healthy:true,origin:'https://legacy.example'}},sent=[];const store={read:()=>structuredClone(disk),mutate:fn=>{const d=structuredClone(disk),r=fn(d);disk=d;return r}};const app=express();app.use(express.json());const server=app.listen(0);t.after(()=>server.close());const base=`http://127.0.0.1:${server.address().port}`;registerPerformanceAgreementRoutes(app,{store,baseUrl:base,auth:(q,s,n)=>q.headers.authorization==='owner'?(q.user={id:'o',role:'owner'},n()):s.sendStatus(401),owner:(q,s,n)=>n(),env:{PERFORMANCE_AGREEMENTS_ENABLED:'true',AGREEMENT_SOURCE_URL:'https://legacy.example',AGREEMENT_SYNC_SECRET:'test',AGREEMENT_SOURCE_IDS:JSON.stringify(['l1','l2','l3','l4','l5','l6','l7']),RESEND_API_KEY:'test'},send:async p=>{sent.push(p);return {status:'accepted',messageId:'email'+sent.length}},...options});const req=(url,body,owner=true,origin=base)=>fetch(base+url,{method:body?'POST':'GET',headers:{'content-type':'application/json',origin,...(owner?{authorization:'owner'}:{})},body:body?JSON.stringify(body):undefined});return {req,store,sent,base};}
async function make(f){const a=await(await f.req('/api/performance-agreements',draft)).json();assert.ok(a.id);return a;}
test('owner and same-origin required; exact approval required and only one delivery occurs',async t=>{const f=await fixture(t);assert.equal((await f.req('/api/performance-agreements',null,false)).status,401);assert.equal((await f.req('/api/performance-agreements',draft,true,'https://evil.example')).status,403);const a=await make(f),url='/api/performance-agreements/'+a.id;assert.equal((await f.req(url+'/send',{hash:a.hash,confirm:true})).status,409);assert.equal((await f.req(url+'/approve',{hash:a.hash,confirm:true})).status,200);assert.equal((await f.req(url+'/send',{hash:a.hash,confirm:true})).status,200);assert.equal(f.sent.length,1);assert.equal((await f.req(url+'/send',{hash:a.hash,confirm:true})).status,409);assert.equal(f.sent.length,1);assert.equal(f.store.read().agreements[0].attempts[0].status,'accepted');assert.equal(f.store.read().agreements[0].attempts[0].providerEvents,undefined)});
test('full public acceptance distinguishes page loads, OTP identity, and replayed acceptance',async t=>{const f=await fixture(t),a=await make(f),url='/api/performance-agreements/'+a.id;await f.req(url+'/approve',{hash:a.hash,confirm:true});await f.req(url+'/send',{hash:a.hash,confirm:true});const token=f.sent[0].text.match(/#token=([\w-]+)/)[1];let r=await f.req('/api/performance-agreements/public/open',{token},false);assert.equal(r.status,200);assert.equal(f.store.read().agreements[0].views.count,1);assert.equal((await f.req('/api/performance-agreements/public/code',{token},false)).status,200);const code=f.sent[1].text.match(/\b\d{6}\b/)[0],p={token,hash:a.hash,fullName:draft.name,email:draft.email,agreed:true,code};r=await f.req('/api/performance-agreements/public/accept',{...p,code:code==='000000'?'111111':'000000'},false);assert.equal(r.status,400);assert.equal(f.store.read().agreements[0].code.attempts,1);const accepted=await(await f.req('/api/performance-agreements/public/accept',p,false)).json();assert.ok(accepted.acceptance.acceptedAt);assert.equal((await f.req(url+'/revoke',{confirm:true})).status,409);assert.deepEqual(await(await f.req('/api/performance-agreements/public/accept',p,false)).json(),accepted);assert.equal(f.sent.length,2);const evidence=await(await f.req(url+'/evidence')).json();assert.equal(evidence.verificationAttempts[0].status,'accepted');assert.equal(evidence.verificationAttempts[0].messageId,'email2');assert.ok(!JSON.stringify(evidence).includes(code))});
test('unknown delivery blocks retry and in-flight send cannot be duplicated',async t=>{let release;const f=await fixture(t,{send:()=>new Promise(r=>release=r)}),a=await make(f),url='/api/performance-agreements/'+a.id;await f.req(url+'/approve',{hash:a.hash,confirm:true});const pending=f.req(url+'/send',{hash:a.hash,confirm:true});while(!release)await new Promise(r=>setTimeout(r,5));assert.equal((await f.req(url+'/send',{hash:a.hash,confirm:true})).status,409);release({status:'unknown'});await pending;assert.equal((await f.req(url+'/send',{hash:a.hash,confirm:true,retry:true})).status,409)});
test('stale legacy reconciliation blocks issuance and provider events never imply signature',async t=>{const f=await fixture(t,{providerLookup:async()=>({id:'email1',last_event:'delivered'})}),a=await make(f),url='/api/performance-agreements/'+a.id;await f.req(url+'/approve',{hash:a.hash,confirm:true});f.store.mutate(d=>d.sync.at='2020-01-01');assert.equal((await f.req(url+'/send',{hash:a.hash,confirm:true})).status,409);f.store.mutate(d=>d.sync.at=new Date().toISOString());await f.req(url+'/send',{hash:a.hash,confirm:true});assert.equal((await f.req(url+'/refresh',{})).status,200);const record=f.store.read().agreements[0];assert.ok(record.attempts[0].providerEvents.delivered);assert.equal(record.acceptance,null);assert.equal(record.views.count,0)});
test('sync rejects corrupt hashes without modifying existing state',async t=>{const f=await fixture(t,{sourceLookup:async()=>({contracts:[{id:'legacy',eventKey:'e',name:'Signer',email:'s@example.com',text:'text',hash:'bad',views:null}]})});const before=f.store.read();assert.equal((await f.req('/api/performance-agreements/sync',{})).status,502);assert.deepEqual(f.store.read().agreements,before.agreements);assert.equal(f.store.read().sync.healthy,false)});
test('incomplete legacy snapshot invalidates sync health immediately and blocks send',async t=>{const f=await fixture(t,{sourceLookup:async()=>({contracts:[{id:'l1',eventKey:'legacy',name:'A',email:'a@example.com',text:'terms',hash:digest('terms'),views:null}]})}),a=await make(f),url='/api/performance-agreements/'+a.id;await f.req(url+'/approve',{hash:a.hash,confirm:true});assert.equal((await f.req('/api/performance-agreements/sync',{})).status,502);assert.equal(f.store.read().sync.healthy,false);assert.equal((await f.req(url+'/send',{hash:a.hash,confirm:true})).status,409);assert.equal(f.sent.length,0)});
test('send rechecks event/recipient duplicates after draft approval',async t=>{const f=await fixture(t),a=await make(f),url='/api/performance-agreements/'+a.id;await f.req(url+'/approve',{hash:a.hash,confirm:true});f.store.mutate(d=>d.agreements.push({...structuredClone(d.agreements[0]),id:'external',source:'external'}));assert.equal((await f.req(url+'/send',{hash:a.hash,confirm:true})).status,409);assert.equal(f.sent.length,0)});
test('verification attempt with uncertain provider result remains inspectable without code disclosure',async t=>{const messages=[];const f=await fixture(t,{send:async p=>{messages.push(p);return messages.length===1?{status:'accepted',messageId:'one'}:{status:'unknown'}}}),a=await make(f),url='/api/performance-agreements/'+a.id;await f.req(url+'/approve',{hash:a.hash,confirm:true});await f.req(url+'/send',{hash:a.hash,confirm:true});const token=messages[0].text.match(/#token=([\w-]+)/)[1];assert.equal((await f.req('/api/performance-agreements/public/code',{token},false)).status,502);const evidence=await(await f.req(url+'/evidence')).json(),code=messages[1].text.match(/\b\d{6}\b/)[0];assert.equal(evidence.verificationAttempts[0].status,'unknown');assert.ok(!JSON.stringify(evidence).includes(code));assert.ok(!JSON.stringify(evidence).includes(token))});
