<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dashboard • KVN Live Tickets</title><link rel="stylesheet" href="/styles.css"></head><body><div class="dash">
<aside class="sidebar"><a class="brand" href="/"><span class="brand-mark">KV</span><span>KVN LIVE TICKETS</span></a><nav id="dashNav"><button class="active" data-panel="overview">Overview</button><button data-panel="events">Events</button><button data-panel="builder">Page Builder</button><button data-panel="orders">Orders & Attendees</button><button data-panel="discounts">Discounts</button><button data-panel="organizations" class="owner-only">Organizations</button><button data-panel="settings" class="owner-only">Platform Settings</button></nav><div style="position:absolute;bottom:20px;left:22px;right:22px"><div class="muted" id="whoami">Not signed in</div><button class="btn small" style="width:100%;margin-top:8px" onclick="location.href='/'">Public Site</button></div></aside>
<main class="dash-main"><div id="loginGate"><div class="card" style="max-width:620px;margin:10vh auto"><span class="kicker">DEMO ACCESS</span><h1>KVN Dashboard</h1><p class="muted">Use owner mode to control the entire platform, approvals and all organizers. Use organizer mode to see the exact workspace a church or partner group receives.</p><div class="inline-actions"><button class="btn primary" id="demoOwner">Enter as Owner</button><button class="btn secondary" id="demoOrganizer">Enter as Organizer</button></div><p class="muted" style="font-size:12px">For production, replace demo sign-in with Auth0, Clerk, Supabase Auth, Firebase Auth, or your preferred identity provider.</p></div></div>
<div id="dashboard" hidden><div class="dash-top"><div><span class="kicker" id="roleLabel">DASHBOARD</span><h1 style="margin:4px 0">Control Center</h1></div><div class="inline-actions"><a href="/checkin.html" class="btn">Check-In</a><button class="btn primary" id="newEvent">+ New Event</button></div></div>
<section class="panel active" id="panel-overview"><div class="metrics"><div class="metric"><span class="muted">Gross sales</span><strong id="mGross">$0</strong></div><div class="metric"><span class="muted">Orders</span><strong id="mOrders">0</strong></div><div class="metric"><span class="muted">Tickets issued</span><strong id="mTickets">0</strong></div><div class="metric"><span class="muted">Events</span><strong id="mEvents">0</strong></div></div><div class="section"><div class="section-head"><div><span class="kicker">RECENT</span><h2>Event Activity</h2></div></div><div id="overviewEvents" class="grid"></div></div></section>
<section class="panel" id="panel-events"><div class="section-head"><div><span class="kicker">EVENT MANAGER</span><h2>Your Events</h2></div><button class="btn primary" onclick="openNewEvent()">Create Event</button></div><div id="eventsTable"></div></section>
<section class="panel" id="panel-builder"><div class="section-head"><div><span class="kicker">NO-CODE BUILDER</span><h2>Drag & Drop Page Builder</h2></div><div class="inline-actions"><select id="builderEvent"></select><button class="btn primary" id="saveBuilder">Save Page</button></div></div><div class="builder"><div class="builder-tools"><strong>Add Blocks</strong><p class="muted">Drag a block into the canvas or click to add.</p><div class="tool" draggable="true" data-newtype="hero">Hero</div><div class="tool" draggable="true" data-newtype="details">Event Details</div><div class="tool" draggable="true" data-newtype="tickets">Tickets</div><div class="tool" draggable="true" data-newtype="apparel">Apparel</div><div class="tool" draggable="true" data-newtype="text">Text / Story</div><div class="tool" draggable="true" data-newtype="cta">Call to Action</div><hr style="border-color:#2a2a2a"><button class="btn" style="width:100%" id="addProduct">+ Ticket / Apparel</button><button class="btn" style="width:100%;margin-top:8px" id="editEventInfo">Edit Event Info</button></div><div class="builder-canvas" id="builderCanvas"></div><div class="builder-settings"><strong>Selected Block</strong><p class="muted">Click any block to edit it.</p><div id="blockSettings"><p class="muted">Nothing selected.</p></div></div></div></section>
<section class="panel" id="panel-orders"><div class="section-head"><div><span class="kicker">SALES + CRM</span><h2>Orders & Attendees</h2></div><a class="btn" href="/checkin.html">Open Check-In</a></div><div id="ordersTable"></div></section>
<section class="panel" id="panel-discounts"><div class="section-head"><div><span class="kicker">PROMOTIONS</span><h2>Discount Codes</h2></div><button class="btn primary" id="newDiscount">New Code</button></div><div id="discountTable"></div></section>
<section class="panel owner-only" id="panel-organizations"><div class="section-head"><div><span class="kicker">OWNER CONTROL</span><h2>Organizations</h2></div></div><div id="orgTable"></div></section>
<section class="panel owner-only" id="panel-settings"><div class="section-head"><div><span class="kicker">PLATFORM</span><h2>Owner Settings</h2></div></div><div class="card"><p><strong>Platform commission:</strong> <span id="feePct"></span>%</p><p><strong>Organizer approval:</strong> Required</p><p class="muted">Stripe Connect is wired into the backend so approved organizers can receive destination payouts while KVN retains an application fee. Production onboarding requires your Stripe platform account.</p></div></section>
</div></main></div>
<div class="modal" id="modal"><div class="modal-card"><div class="drawer-head"><h2 id="modalTitle">Edit</h2><button class="btn small" onclick="closeModal()">Close</button></div><div id="modalBody"></div></div></div><script src="/dashboard.js"></script></body></html>
