const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((c||0)/100);let token=localStorage.getItem('kvn_token')||'';let data=null;let selectedBlock=null;let builderLayout=[];const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,opt={}){opt.headers={...(opt.headers||{}),Authorization:`Bearer ${token}`};if(opt.body&&!opt.headers['Content-Type'])opt.headers['Content-Type']='application/json';const r=await fetch(url,opt);const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d}
async function demo(role){const r=await fetch('/api/auth/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role})});const d=await r.json();token=d.token;localStorage.setItem('kvn_token',token);await loadDashboard()}
demoOwner.onclick=()=>demo('owner');demoOrganizer.onclick=()=>demo('organizer');
async function loadDashboard(){try{data=await api('/api/dashboard');loginGate.hidden=true;dashboard.hidden=false;whoami.textContent=`${data.user.name} • ${data.user.role}`;roleLabel.textContent=data.user.role==='owner'?'PLATFORM OWNER':'ORGANIZER WORKSPACE';document.querySelectorAll('.owner-only').forEach(x=>x.style.display=data.user.role==='owner'?'':'none');renderAll()}catch(e){loginGate.hidden=false;dashboard.hidden=true}}
function renderAll(){mGross.textContent=money(data.metrics.gross);mOrders.textContent=data.metrics.orders;mTickets.textContent=data.metrics.tickets;mEvents.textContent=data.metrics.events;feePct.textContent=data.settings.platformFeePercent;renderOverview();renderEvents();renderOrders();renderDiscounts();renderOrgs();builderEvent.innerHTML=data.events.map(e=>`<option value="${e.id}">${esc(e.title)}</option>`).join('');if(data.events.length)loadBuilder(data.events[0].id)}
function renderOverview(){overviewEvents.innerHTML=data.events.slice(0,6).map(e=>`<div class="event-card"><div><span class="status ${e.status}">${e.status}</span><h3>${esc(e.title)}</h3><div class="event-meta">${esc(e.location)}</div></div><div class="inline-actions"><button class="btn small" onclick="editEvent('${e.id}')">Edit</button>${data.user.role==='owner'&&e.status==='pending'?`<button class="btn small primary" onclick="statusEvent('${e.id}','published')">Approve</button>`:''}</div></div>`).join('')||'<div class="card">No events yet.</div>'}
function table(rows,heads){return `<div class="table-wrap"><table class="table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function renderEvents(){eventsTable.innerHTML=table(data.events.map(e=>`<tr><td><strong>${esc(e.title)}</strong><div class="muted">${esc(e.slug)}</div></td><td><span class="status ${e.status}">${e.status}</span></td><td>${new Date(e.date).toLocaleDateString()}</td><td>${e.products.reduce((n,p)=>n+p.sold,0)} sold</td><td><div class="inline-actions"><button class="btn small" onclick="openBuilder('${e.id}')">Build</button><button class="btn small" onclick="editEvent('${e.id}')">Edit</button>${data.user.role==='owner'&&e.status==='pending'?`<button class="btn small primary" onclick="statusEvent('${e.id}','published')">Approve</button>`:''}${e.status==='published'?`<a class="btn small" target="_blank" href="/event.html?slug=${encodeURIComponent(e.slug)}">View</a>`:''}</div></td></tr>`),['Event','Status','Date','Sales','Actions'])}
function renderOrders(){ordersTable.innerHTML=table(data.orders.map(o=>`<tr><td><strong>${esc(o.id)}</strong><div class="muted">${new Date(o.createdAt).toLocaleString()}</div></td><td>${esc(o.buyerName||'')}<div class="muted">${esc(o.buyerEmail||'')}</div></td><td><span class="status ${o.status}">${o.status}</span></td><td>${o.tickets?.length||0}</td><td>${money(o.amountTotal)}</td><td>${o.status==='paid'?`<button class="btn small danger" onclick="refund('${o.id}')">Refund</button>`:''}</td></tr>`),['Order','Buyer','Status','Tickets','Total','Action'])}
function renderDiscounts(){discountTable.innerHTML=table(data.discounts.map(d=>`<tr><td><strong>${esc(d.code)}</strong></td><td>${d.type==='percent'?`${d.value}%`:money(d.value)}</td><td>${d.uses} / ${d.maxUses}</td><td>${d.active?'Active':'Disabled'}</td></tr>`),['Code','Value','Uses','Status'])}
function renderOrgs(){if(data.user.role!=='owner')return;orgTable.innerHTML=table(data.organizations.map(o=>`<tr><td><strong>${esc(o.name)}</strong><div class="muted">${esc(o.slug)}</div></td><td><span class="status ${o.status}">${o.status}</span></td><td>${o.stripeAccountId?'Connected':'Not connected'}</td><td>${o.status==='pending'?`<button class="btn small primary" onclick="approveOrg('${o.id}')">Approve</button>`:''}</td></tr>`),['Organization','Status','Payouts','Action'])}
function switchPanel(name){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.getElementById(`panel-${name}`).classList.add('active');document.querySelectorAll('#dashNav button').forEach(b=>b.classList.toggle('active',b.dataset.panel===name))}dashNav.querySelectorAll('button').forEach(b=>b.onclick=()=>switchPanel(b.dataset.panel));
function openModal(title,html){modalTitle.textContent=title;modalBody.innerHTML=html;modal.classList.add('open')}window.closeModal=()=>modal.classList.remove('open');
window.openNewEvent=()=>openModal('Create Event',`<form id="eventForm" class="form-stack"><label>Event name<input name="title" required></label><label>Subtitle<input name="subtitle"></label><div class="two-col"><label>Date & time<input type="datetime-local" name="date" required></label><label>Venue<input name="venue"></label></div><label>City / Location<input name="location"></label><label>Description<textarea name="description"></textarea></label><button class="btn primary">Create Event</button></form>`);newEvent.onclick=openNewEvent;
modal.addEventListener('submit',async e=>{if(e.target.id==='eventForm'){e.preventDefault();const body=Object.fromEntries(new FormData(e.target));await api('/api/events',{method:'POST',body:JSON.stringify(body)});closeModal();await refresh()}if(e.target.id==='editEventForm'){e.preventDefault();const id=e.target.dataset.id,body=Object.fromEntries(new FormData(e.target));await api(`/api/events/${id}`,{method:'PUT',body:JSON.stringify(body)});closeModal();await refresh()}if(e.target.id==='productForm'){e.preventDefault();const fd=Object.fromEntries(new FormData(e.target));fd.price=Math.round(Number(fd.price)*100);fd.inventory=Number(fd.inventory);if(fd.type==='apparel')fd.options={size:(fd.sizes||'S,M,L,XL,2XL').split(',').map(x=>x.trim()).filter(Boolean)};delete fd.sizes;await api(`/api/events/${fd.eventId}/products`,{method:'POST',body:JSON.stringify(fd)});closeModal();await refresh()}if(e.target.id==='discountForm'){e.preventDefault();const fd=Object.fromEntries(new FormData(e.target));if(fd.type==='fixed')fd.value=Math.round(Number(fd.value)*100);await api('/api/discounts',{method:'POST',body:JSON.stringify(fd)});closeModal();await refresh()}});
async function refresh(){data=await api('/api/dashboard');renderAll()}
window.editEvent=id=>{const e=data.events.find(x=>x.id===id);openModal('Edit Event',`<form id="editEventForm" data-id="${id}" class="form-stack"><label>Event name<input name="title" value="${esc(e.title)}"></label><label>Subtitle<input name="subtitle" value="${esc(e.subtitle)}"></label><div class="two-col"><label>Date/time<input name="date" value="${esc(e.date)}"></label><label>Venue<input name="venue" value="${esc(e.venue)}"></label></div><label>Location<input name="location" value="${esc(e.location)}"></label><label>Description<textarea name="description">${esc(e.description)}</textarea></label><button class="btn primary">Save</button></form>`)}
window.statusEvent=async(id,status)=>{await api(`/api/events/${id}/status`,{method:'POST',body:JSON.stringify({status})});await refresh()};window.approveOrg=async id=>{await api(`/api/organizations/${id}/approve`,{method:'POST'});await refresh()};window.refund=async id=>{if(!confirm('Issue a full Stripe refund for this order?'))return;try{await api(`/api/orders/${id}/refund`,{method:'POST'});await refresh()}catch(e){alert(e.message)}};
function loadBuilder(id){const e=data.events.find(x=>x.id===id);if(!e)return;builderEvent.value=id;builderLayout=JSON.parse(JSON.stringify(e.layout||[]));selectedBlock=null;renderBuilder()}builderEvent.onchange=()=>loadBuilder(builderEvent.value);window.openBuilder=id=>{switchPanel('builder');loadBuilder(id)};
function renderBuilder(){builderCanvas.innerHTML=builderLayout.length?'':'<div class="empty-drop">Drop blocks here</div>';builderLayout.forEach((b,i)=>{const el=document.createElement('div');el.className='canvas-block'+(selectedBlock===b.id?' selected':'');el.draggable=true;el.dataset.id=b.id;el.innerHTML=`<span class="badge">${esc(b.type)}</span><h3>${esc(b.title)}</h3><p class="muted">${esc(b.body)}</p><small class="muted">Drag to reorder • Click to edit</small>`;el.onclick=()=>{selectedBlock=b.id;renderBuilder();renderSettings()};el.ondragstart=e=>{e.dataTransfer.setData('text/block-id',b.id);el.classList.add('dragging')};el.ondragend=()=>el.classList.remove('dragging');el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();const moving=e.dataTransfer.getData('text/block-id');if(!moving)return;const from=builderLayout.findIndex(x=>x.id===moving),to=i;if(from>=0){const [x]=builderLayout.splice(from,1);builderLayout.splice(to,0,x);renderBuilder()}};builderCanvas.appendChild(el)});renderSettings()}
function renderSettings(){const b=builderLayout.find(x=>x.id===selectedBlock);if(!b){blockSettings.innerHTML='<p class="muted">Nothing selected.</p>';return}blockSettings.innerHTML=`<div class="form-stack"><label>Block type<select id="setType">${['hero','details','tickets','apparel','text','cta'].map(t=>`<option ${t===b.type?'selected':''}>${t}</option>`).join('')}</select></label><label>Heading<input id="setTitle" value="${esc(b.title)}"></label><label>Text<textarea id="setBody">${esc(b.body)}</textarea></label><button class="btn danger" id="deleteBlock">Delete Block</button></div>`;setType.onchange=()=>{b.type=setType.value;renderBuilder()};setTitle.oninput=()=>{b.title=setTitle.value;renderBuilder()};setBody.oninput=()=>{b.body=setBody.value;renderBuilder()};deleteBlock.onclick=()=>{builderLayout=builderLayout.filter(x=>x.id!==b.id);selectedBlock=null;renderBuilder()}}
function addBlock(type){const b={id:`b_${Math.random().toString(36).slice(2,9)}`,type,title:type==='tickets'?'Tickets':type==='apparel'?'Apparel':type==='hero'?'Event Hero':'New Section',body:'Click this block to edit its content.'};builderLayout.push(b);selectedBlock=b.id;renderBuilder()}
document.querySelectorAll('[data-newtype]').forEach(t=>{t.onclick=()=>addBlock(t.dataset.newtype);t.ondragstart=e=>e.dataTransfer.setData('text/new-type',t.dataset.newtype)});builderCanvas.ondragover=e=>e.preventDefault();builderCanvas.addEventListener('drop',e=>{const type=e.dataTransfer.getData('text/new-type');if(type)addBlock(type)});saveBuilder.onclick=async()=>{const id=builderEvent.value;await api(`/api/events/${id}`,{method:'PUT',body:JSON.stringify({layout:builderLayout})});await refresh();alert('Page layout saved.')};
addProduct.onclick=()=>{const id=builderEvent.value;openModal('Add Ticket or Apparel',`<form id="productForm" class="form-stack"><input type="hidden" name="eventId" value="${id}"><label>Type<select name="type"><option value="ticket">Ticket</option><option value="apparel">Apparel</option></select></label><label>Name<input name="name" required></label><label>Description<textarea name="description"></textarea></label><div class="two-col"><label>Price ($)<input type="number" step="0.01" name="price" required></label><label>Inventory<input type="number" name="inventory" required></label></div><label>Apparel sizes (comma separated)<input name="sizes" value="S,M,L,XL,2XL,3XL"></label><button class="btn primary">Add Product</button></form>`)};editEventInfo.onclick=()=>editEvent(builderEvent.value);newDiscount.onclick=()=>openModal('New Discount Code',`<form id="discountForm" class="form-stack"><label>Event<select name="eventId">${data.events.map(e=>`<option value="${e.id}">${esc(e.title)}</option>`).join('')}</select></label><label>Code<input name="code" required placeholder="KINGDOM10"></label><label>Type<select name="type"><option value="percent">Percent off</option><option value="fixed">Fixed dollars off</option></select></label><label>Value<input name="value" type="number" step="0.01" required></label><label>Maximum uses<input name="maxUses" type="number" value="100"></label><button class="btn primary">Create Code</button></form>`);
loadDashboard();
