import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';import {chromium} from 'playwright';
import {registerPerformanceAgreementRoutes} from '../lib/performance-agreement-routes.js';
for(const width of [320,390])test(`performance agreement owner review and signer acceptance at ${width}px`,async t=>{
 let disk={agreements:[],sync:{at:new Date().toISOString(),healthy:true,origin:'https://legacy.example'}},mail=[];
 const store={read:()=>structuredClone(disk),mutate:fn=>{const d=structuredClone(disk),r=fn(d);disk=d;return r}},app=express();app.use(express.json());
 app.get('/owner',(q,s)=>s.send('<html><head><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/performance-agreements-dashboard.css"></head><body><div id="agreementsRoot"></div><dialog id="agreementsDialog"></dialog><script src="/performance-agreements.js"></script><script>KVNAgreements.init({user:{role:"owner"},api:async(url,opt={})=>{const r=await fetch(url,{...opt,headers:{"content-type":"application/json"}});const p=await r.json();if(!r.ok)throw Error(p.error);return p}})</script></body></html>'));
 app.use(express.static('public'));const server=app.listen(0);t.after(()=>server.close());const base=`http://127.0.0.1:${server.address().port}`;
 registerPerformanceAgreementRoutes(app,{store,baseUrl:base,auth:(q,s,n)=>{q.user={id:'owner'};n()},owner:(q,s,n)=>n(),env:{PERFORMANCE_AGREEMENTS_ENABLED:'true',RESEND_API_KEY:'fake',AGREEMENT_SOURCE_URL:'https://legacy.example',AGREEMENT_SYNC_SECRET:'fake',AGREEMENT_SOURCE_IDS:JSON.stringify(['1','2','3','4','5','6','7'])},send:async p=>{mail.push(p);return {status:'accepted',messageId:'fake'+mail.length}}});
 const browser=await chromium.launch({headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width,height:844}});await page.goto(base+'/owner');await page.getByText('New draft',{exact:true}).click();await page.locator('[name=eventKey]').fill('TEST-EVENT');await page.locator('[name=name]').fill('Test Signer');await page.locator('[name=email]').fill('test@example.com');const text='Final test terms. $400 fee. '+('Long finalized agreement text. '.repeat(80));await page.locator('[name=text]').fill(text);await page.getByText('Save draft for review',{exact:true}).click();await page.getByText('Approve this version',{exact:true}).waitFor();await page.locator('#agreementConfirm').check();await page.getByText('Approve this version',{exact:true}).click();await page.getByText('Issue agreement by email',{exact:true}).waitFor();await page.locator('#agreementConfirm').check();page.once('dialog',d=>d.accept());await page.getByText('Issue agreement by email',{exact:true}).click();await page.getByText('Revoke unsigned agreement',{exact:true}).waitFor();assert.equal(mail.length,1);
 assert.ok(await page.locator('#agreementsDialog').evaluate(e=>e.scrollWidth<=e.clientWidth+2),'dialog overflows phone viewport');
 const token=mail[0].text.match(/#token=([\w-]+)/)[1];await page.goto(base+'/performance-agreement.html#token='+token);await page.locator('#terms').waitFor({state:'visible'});assert.equal(await page.locator('#terms').textContent(),text);await page.getByText('Email my verification code',{exact:true}).click();await page.getByText('Verification email accepted by provider. Check your inbox.',{exact:true}).waitFor();await page.locator('#code').fill(mail[1].text.match(/\b\d{6}\b/)[0]);await page.locator('#name').fill('Test Signer');await page.locator('#email').fill('test@example.com');await page.locator('#consent').check();await page.getByText('I agree and accept',{exact:true}).click();await page.locator('#accepted').waitFor({state:'visible'});assert.equal(disk.agreements[0].acceptance.text,text);assert.equal(disk.agreements[0].attempts[0].status,'accepted');assert.equal(disk.agreements[0].views.count,1);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'signing page overflows phone viewport');await page.reload();await page.locator('#accepted').waitFor({state:'visible'});assert.equal(mail.length,2);
});
