import crypto from 'node:crypto';
import {ensureMarketing,cleanCsv,importContacts,upsertContact,syncContacts,parseCsv,exportContacts,eligibleContacts,campaignContent,recoveryPreview,validateDraft,fail,uid,stamp,normEmail,escapeHtml,defaults} from './marketing.js';
export async function sendMarketingEmail({to,content,key},{env=process.env,fetchImpl=fetch}={}){
 if(!env.RESEND_API_KEY)return {status:'failed',error:'Email provider is not configured.'};
 try{const r=await fetchImpl('https://api.resend.com/emails',{method:'POST',signal:AbortSignal.timeout(15000),headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({from:'Kingdom Vibe Network <info@tickets.kvnlive.com>',to:[to],...content})});const data=await r.json().catch(()=>({}));if(r.ok&&data.id)return {status:'accepted',messageId:data.id};return {status:r.status>=500||r.ok?'unknown':'failed',error:`Email provider returned ${r.status}. ${String(data.message||'Review provider logs before retrying.').slice(0,300)}`};}catch{return {status:'unknown',error:'Delivery request did not return a definite result. Review provider logs; do not resend blindly.'}}}
export function registerMarketingRoutes(app,{auth,owner,readStore,writeStore,baseUrl,engagement,env=process.env,send=payload=>sendMarketingEmail(payload,{env}),delayMs=550}){
 const read=()=>ensureMarketing(readStore());let busy=false;
 const blocked=d=>engagement?.blockedEmails(d)||new Set();
 const eligible=(d,ids)=>{const suppressed=blocked(d);return eligibleContacts(d,ids).filter(c=>!suppressed.has(normEmail(c.email)))};
 const tracking=()=>({webhookConfigured:!!env.RESEND_MARKETING_WEBHOOK_SECRET,...engagement?.status()});
 const safe=fn=>async(q,s)=>{try{await fn(q,s)}catch(e){s.status(e.statusCode||500).json({error:e.statusCode?e.message:'Unable to complete this request.'})}};
 const sameOrigin=(q,s,n)=>{if(q.headers.origin!==new URL(baseUrl).origin||q.headers['sec-fetch-site']==='cross-site')return s.status(403).json({error:'Use the signed-in dashboard.'});n()};
 const get=(path,fn)=>app.get(path,auth,owner,safe(fn));const post=(path,fn)=>app.post(path,auth,owner,sameOrigin,safe(fn));const patch=(path,fn)=>app.patch(path,auth,owner,sameOrigin,safe(fn));
 const audit=(d,q,action,id)=>{d.auditLogs??=[];d.auditLogs.unshift({id:uid(),userId:q.user.id,userName:q.user.name||'Owner',action,entityType:'marketing',entityId:id,createdAt:stamp()})};
 const campaign=(d,id)=>{const c=d.marketing.campaigns.find(c=>c.id===id);if(!c)throw fail('Campaign not found.',404);return c};
 const ready=d=>{if(!env.RESEND_API_KEY)throw fail('Email provider is not configured.',503);if(!d.marketing.settings.mailingAddress.trim())throw fail('Save your mailing address in Email Settings before sending.')};
 const preview=(d,c)=>{const audience=eligible(d,c.listIds).map(x=>({id:x.id,email:x.email})).sort((a,b)=>a.id.localeCompare(b.id));const previewToken=crypto.createHash('sha256').update(JSON.stringify({revision:c.revision,audience,settings:d.marketing.settings})).digest('hex');return {count:audience.length,previewToken,content:campaignContent(c,{unsubscribeToken:'preview'},d.marketing.settings,baseUrl),audience}};
 const filtered=(d,q)=>d.marketing.contacts.filter(c=>(q.archived==='true'?!!c.archivedAt:!c.archivedAt)&&(!q.list||c.listIds.includes(q.list))&&(!q.permission||c.permission===q.permission)&&(!q.search||`${c.name} ${c.email}`.toLowerCase().includes(String(q.search).toLowerCase())));
 get('/api/marketing',(q,s)=>{const d=read(),m=d.marketing,rows=filtered(d,q.query),suppressed=blocked(d),page=Math.max(1,parseInt(q.query.page)||1);s.json({lists:m.lists.map(l=>({...l,total:m.contacts.filter(c=>!c.archivedAt&&c.listIds.includes(l.id)).length,subscribed:eligible(d,[l.id]).length})),contacts:rows.slice((page-1)*50,page*50).map(({unsubscribeToken,...c})=>({...c,providerSuppressed:suppressed.has(normEmail(c.email))})),tracking:tracking(),total:rows.length,page,settings:m.settings,configured:!!env.RESEND_API_KEY,campaigns:m.campaigns.slice().reverse().map(({recipients,...c})=>({...c,engagement:engagement?.report({recipients}).summary,counts:(recipients||[]).reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{})}))})});
 post('/api/marketing/sync',(q,s)=>{const d=read(),result=syncContacts(d);audit(d,q,'marketing.sync','contacts');writeStore(d);s.json(result)});
 post('/api/marketing/lists',(q,s)=>{const d=read(),name=String(q.body.name||'').trim();if(!name||name.length>100||d.marketing.lists.some(l=>l.name.toLowerCase()===name.toLowerCase()))throw fail('Enter a unique list name (1–100 characters).');const list={id:uid(),name};d.marketing.lists.push(list);writeStore(d);s.json(list)});
 patch('/api/marketing/lists/:id',(q,s)=>{const d=read(),l=d.marketing.lists.find(l=>l.id===q.params.id),name=String(q.body.name||'').trim();if(!l)throw fail('List not found.',404);if(!name||name.length>100||d.marketing.lists.some(other=>other.id!==l.id&&other.name.toLowerCase()===name.toLowerCase()))throw fail('Enter a unique list name.');l.name=name;writeStore(d);s.json(l)});
 app.delete('/api/marketing/lists/:id',auth,owner,sameOrigin,safe((q,s)=>{const d=read();if(defaults.some(([id])=>id===q.params.id))throw fail('Source lists can be renamed but cannot be deleted.');if(d.marketing.campaigns.some(c=>!['complete','cancelled'].includes(c.status)&&c.listIds.includes(q.params.id)))throw fail('This list is used by an active campaign.',409);d.marketing.lists=d.marketing.lists.filter(l=>l.id!==q.params.id);d.marketing.contacts.forEach(c=>c.listIds=c.listIds.filter(id=>id!==q.params.id));writeStore(d);s.json({ok:true})}));
 post('/api/marketing/contacts',(q,s)=>{const d=read(),c=upsertContact(d,q.body);audit(d,q,'marketing.contact.save',c.id);writeStore(d);s.json({id:c.id})});
 patch('/api/marketing/contacts/:id',(q,s)=>{const d=read(),c=d.marketing.contacts.find(c=>c.id===q.params.id);if(!c)throw fail('Contact not found.',404);upsertContact(d,{...q.body,email:c.email});if(q.body.listIds)c.listIds=[...new Set(q.body.listIds)];if(typeof q.body.archived==='boolean')c.archivedAt=q.body.archived?stamp():null;audit(d,q,'marketing.contact.update',c.id);writeStore(d);s.json({id:c.id})});
 post('/api/marketing/clean-csv',(q,s)=>{const result=cleanCsv(q.body.csv);s.json({...result,sample:result.rows.slice(0,5).map(({email,name})=>({email,name})),rows:undefined,rejected:undefined,valid:result.rows.length,rejectedCount:result.rejected.length})});
 post('/api/marketing/import',(q,s)=>{const d=read(),result=importContacts(d,q.body);audit(d,q,'marketing.import',String(result.imported));writeStore(d);s.json(result)});
 get('/api/marketing/contacts.csv',(q,s)=>{const d=read(),label=d.marketing.lists.find(l=>l.id===q.query.list)?.name||'all-email-contacts',filename=label.replace(/[^a-z0-9_-]+/gi,'-').slice(0,100);s.set('Content-Type','text/csv; charset=utf-8').set('Content-Disposition',`attachment; filename="kvn-${filename}.csv"`).send(exportContacts(filtered(d,q.query),d.marketing.lists))});
 patch('/api/marketing/settings',(q,s)=>{const d=read(),senderName=String(q.body.senderName||'').trim(),mailingAddress=String(q.body.mailingAddress||'').trim();if(!senderName||senderName.length>100||mailingAddress.length>500)throw fail('Enter a sender name and mailing address under 500 characters.');d.marketing.settings={senderName,mailingAddress};audit(d,q,'marketing.settings','settings');writeStore(d);s.json({ok:true})});
 post('/api/marketing/campaigns',(q,s)=>{const d=read(),c={...validateDraft(q.body,d.marketing),id:uid(),revision:1,status:'draft',createdAt:stamp(),recipients:[]};d.marketing.campaigns.push(c);audit(d,q,'marketing.campaign.create',c.id);writeStore(d);s.json(c)});
 patch('/api/marketing/campaigns/:id',(q,s)=>{const d=read(),c=campaign(d,q.params.id);if(c.status!=='draft'||q.body.revision!==c.revision)throw fail('Campaign changed or already started. Reload it.',409);Object.assign(c,validateDraft(q.body,d.marketing));c.revision++;writeStore(d);s.json(c)});
 get('/api/marketing/campaigns/:id/preview',(q,s)=>{const d=read(),c=campaign(d,q.params.id);s.json({...preview(d,c),audience:undefined,campaign:c})});
 get('/api/marketing/campaigns/:id/engagement',(q,s)=>{
  if(!engagement)throw fail('Engagement reporting is not configured.',503);
  const c=campaign(read(),q.params.id),report=engagement.report(c),search=String(q.query.search||'').toLowerCase().slice(0,200),event=String(q.query.event||'');
  if(event&&!['delivered','opened','clicked','bounced','complained','failed','suppressed','delivery_delayed','unconfirmed'].includes(event))throw fail('Invalid engagement filter.');
  const rows=report.recipients.filter(r=>(!search||r.email.toLowerCase().includes(search))&&(!event||(event==='unconfirmed'?r.engagement.delivery==='unconfirmed':!!r.engagement.observed[event])));
  const pages=Math.max(1,Math.ceil(rows.length/50)),page=Math.min(pages,Math.max(1,parseInt(q.query.page)||1));
  s.set('Cache-Control','no-store').json({campaignId:c.id,subject:c.subject,summary:report.summary,tracking:tracking(),total:rows.length,page,pages,recipients:rows.slice((page-1)*50,page*50).map(r=>({...r,engagement:{...r.engagement,eventCount:r.engagement.events.length,events:r.engagement.events.slice(-50)}}))});
 });
 get('/api/marketing/campaigns/:id/history',(q,s)=>{s.json({recipients:campaign(read(),q.params.id).recipients})});
 post('/api/marketing/campaigns/:id/test',async(q,s)=>{const d=read(),c=campaign(d,q.params.id);ready(d);if(c.lastTestAt&&Date.now()-Date.parse(c.lastTestAt)<60000)throw fail('Wait one minute between test emails.',429);c.lastTestAt=stamp();writeStore(d);const content=campaignContent(c,{unsubscribeToken:'preview'},d.marketing.settings,baseUrl);content.subject='[TEST] '+content.subject;delete content.headers;const testRecipient=normEmail(env.OWNER_EMAIL||q.user.email);const result=await send({to:testRecipient,content,key:'marketing-test-'+uid()});const latest=read();campaign(latest,c.id).lastTestResult=result;writeStore(latest);s.status(result.status==='accepted'?200:502).json({...result,to:testRecipient})});
 post('/api/marketing/campaigns/:id/pause',(q,s)=>{const d=read(),c=campaign(d,q.params.id);if(!['sending','paused'].includes(c.status))throw fail('Only an active campaign can be paused.',409);c.status='paused';writeStore(d);s.json({ok:true})});
 post('/api/marketing/campaigns/:id/cancel',(q,s)=>{const d=read(),c=campaign(d,q.params.id);if(c.status==='complete')throw fail('Campaign already completed.',409);c.status='cancelled';c.recipients.forEach(r=>{if(r.status==='pending')r.status='cancelled'});writeStore(d);s.json({ok:true})});
 post('/api/marketing/campaigns/:id/send',async(q,s)=>{
  if(busy)throw fail('Another email batch is sending. Try again shortly.',409);let d=read(),c=campaign(d,q.params.id);ready(d);if(!['draft','sending','paused'].includes(c.status))throw fail('Campaign already completed or cancelled.',409);
  if(c.status==='draft'){const p=preview(d,c);if(q.body.previewToken!==p.previewToken)throw fail('Audience or draft changed. Preview again before sending.',409);if(!p.count)throw fail('No subscribed contacts in the selected lists.');c.recipients=p.audience.map(x=>({...x,status:'pending'}));c.settings={...d.marketing.settings};c.startedAt=stamp()}
  c.status='sending';writeStore(d);busy=true;
  try{let processed=0;for(let i=0;i<5;i++){d=read();c=campaign(d,q.params.id);if(c.status!=='sending')break;const r=c.recipients.find(r=>r.status==='pending');if(!r)break;const contact=d.marketing.contacts.find(x=>x.id===r.id);if(!contact||contact.archivedAt||contact.permission!=='subscribed'||contact.email!==r.email||blocked(d).has(normEmail(r.email))){r.status='skipped';r.error='No longer eligible (permission, archive or provider suppression)';writeStore(d);continue}r.status='sending';r.attemptedAt=stamp();writeStore(d);const content=campaignContent(c,contact,c.settings,baseUrl);let result;try{result=await send({to:r.email,content,key:`campaign-${c.id}-${r.id}`})}catch{result={status:'unknown',error:'Review provider logs before retrying.'}}const latest=read(),current=campaign(latest,c.id).recipients.find(x=>x.id===r.id);Object.assign(current,result,{updatedAt:stamp()});writeStore(latest);processed++;if(delayMs)await new Promise(resolve=>setTimeout(resolve,delayMs))}
   const latest=read(),current=campaign(latest,c.id);if(current.status==='sending'&&!current.recipients.some(r=>r.status==='pending')){current.status='complete';current.completedAt=stamp()}audit(latest,q,'marketing.campaign.batch',c.id);writeStore(latest);s.json({status:current.status,processed,remaining:current.recipients.filter(r=>r.status==='pending').length});
  }finally{busy=false}
 });
 get('/api/marketing/recovery/:id',(q,s)=>{const d=read(),p=recoveryPreview(d,q.params.id,baseUrl);s.json({to:p.to,content:campaignContent(p.draft,p.contact||{unsubscribeToken:'preview'},d.marketing.settings,baseUrl),fingerprint:crypto.createHash('sha256').update(JSON.stringify([p.cart.email,p.cart.updatedAt,p.event.title,d.marketing.settings])).digest('hex')})});
 post('/api/marketing/recovery/:id/send',async(q,s)=>{if(busy)throw fail('Another email batch is sending.',409);const d=read();ready(d);const p=recoveryPreview(d,q.params.id,baseUrl);if(blocked(d).has(p.to))throw fail('This email is blocked by a provider bounce or complaint.',409);const fingerprint=crypto.createHash('sha256').update(JSON.stringify([p.cart.email,p.cart.updatedAt,p.event.title,d.marketing.settings])).digest('hex');if(q.body.fingerprint!==fingerprint)throw fail('Cart changed. Preview again.',409);
  // One reminder per customer per event, even if multiple cart IDs were recorded.
  if(d.abandonedCarts.some(c=>c.eventId===p.cart.eventId&&normEmail(c.email)===p.to&&c.recoveryEmail))throw fail('This customer already has a recovery email for this event.',409);
  const contact=p.contact||upsertContact(d,{email:p.to,listIds:[]},{source:'abandoned cart'});p.cart.recoveryEmail={to:p.to,status:'sending',attemptedAt:stamp()};writeStore(d);busy=true;
  try{let result;try{result=await send({to:p.to,content:campaignContent(p.draft,contact,d.marketing.settings,baseUrl),key:`cart-recovery-${p.cart.id}`})}catch{result={status:'unknown',error:'Review provider logs before retrying.'}}const latest=read(),cart=latest.abandonedCarts.find(c=>c.id===p.cart.id);cart.recoveryEmail={...cart.recoveryEmail,...result,updatedAt:stamp()};audit(latest,q,'marketing.recovery',cart.id);writeStore(latest);s.status(result.status==='accepted'?200:502).json(result)}finally{busy=false}
 });
 app.get('/email/unsubscribe/:token',safe((q,s)=>{if(!read().marketing.contacts.some(c=>c.unsubscribeToken===q.params.token))return s.status(404).send('Link not found.');s.set('Cache-Control','no-store').set('Referrer-Policy','no-referrer').send('<!doctype html><html lang="en"><title>Email preferences</title><meta name="viewport" content="width=device-width"><body style="font:18px Arial;max-width:600px;margin:60px auto;padding:20px"><h1>Kingdom Vibe Network</h1><p>Stop receiving marketing and checkout reminder emails.</p><form method="post"><button style="padding:16px">Unsubscribe</button></form></body></html>')}));
 app.post('/email/unsubscribe/:token',safe((q,s)=>{const d=read(),c=d.marketing.contacts.find(c=>c.unsubscribeToken===q.params.token);if(!c)return s.status(404).send('Link not found.');c.permission='unsubscribed';c.permissionUpdatedAt=stamp();c.evidence='Recipient unsubscribe';writeStore(d);s.set('Cache-Control','no-store').send('You have been unsubscribed from Kingdom Vibe marketing and checkout reminders. Purchase receipts are unaffected.')}));
}
